---
title: ""
pagetitle: "Publications"
output: html_document
---

### Publications

#### Peer-reviewed

**The Autocratic Bias: Self-censorship of Regime Support**, (2021), *Democratization*. [PDF](https://www.tandfonline.com/doi/pdf/10.1080/13510347.2021.1981867?needAccess=true)

**Dealing With Measurement Error in List Experiments: Choosing the Right Control List Design**, (2021) w. Mattias Agerberg, *Research & Politics*. [PDF](https://journals.sagepub.com/doi/pdf/10.1177/20531680211013154)

**Claiming the Right to Rule: Regime Legitimation Strategies, 1900 to 2019**, (2021), w. Michael Bernhard, Johannes Gerschewski, Anna Lührmann and Christian von Soest, *European Political Science Review*, 13(1), p. 77-94. [PDF](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/6394D262B708B6199B115DFFEE11BE7C/S1755773920000363a.pdf/claiming_the_right_to_rule_regime_legitimation_strategies_from_1900_to_2019.pdf)

**Self-Censorship in Authoritarian States: Evidence from list experiments in China**, (2019)) w. Darrel Robinson,  *Research & Politics*. [PDF](https://journals.sagepub.com/doi/full/10.1177/2053168019856449)

**Regimes of the World (RoW): Opening New Avenues for the Comparative Study of Political Regimes.**, (2018), w. Anna Lührmannand Staffan I. Lindberg, *Politics and Governance*, 6(1), p. 60–77. [PDF](https://www.cogitatiopress.com/politicsandgovernance/article/download/1214/1214), [ShinyApp](https://tannenberg.shinyapps.io/regimes-of-the-world/)

***

#### Editor-reviewed

**Autocratic Aid and Democratic Attitudes**, (2019), *American Political Science Association - The Annals of Comparative Democratization*, 17(2), p. 17-20. [PDF](https://gallery.mailchimp.com/195d6bf7bad75a3ef81189778/files/96ee2113-2c81-44e2-905d-6c7309e7e3e7/APSA_June2019.pdf) 

***

#### Policy reports

**Making Development Work: The Quality of Government Approach*** w. Bo Rothstein, The Expert Group for Aid Studies (EBA) Report, 2015:07. [PDF](https://eba.se/wp-content/uploads/2015/12/Making_development_work_07.pdf)

***

#### Working papers

**On the Road to Better Governance: The "Middle Class Particularism" and Quality of Government** The Quality of Government Institute Working Paper Series, 2014:09.




