---
title: ""
pagetitle: "Publications"
output: html_document
---

### Publications

#### Peer-reviewed articles

**Self-Censorship in Authoritarian States: Evidence from list experiments in China**, (2019)) w. [Darrel Robinson](http://www.darrelrobinson.com/), *Research & Politics* [PDF](https://journals.sagepub.com/doi/full/10.1177/2053168019856449)

**Regimes of the World (RoW): Opening New Avenues for the Comparative Study of Political Regimes.**, (2018), w. [Anna Lührmann](https://sites.google.com/view/anna-luehrmann/) and Staffan I. Lindberg, *Politics and Governance*, 6(1), p. 60–77. [PDF](https://www.cogitatiopress.com/politicsandgovernance/article/download/1214/1214), [ShinyApp](https://tannenberg.shinyapps.io/regimes-of-the-world/)

***

#### Working Papers

**Regime Legitimation Strategies (RLS) 1900 to 2018** w. Michael Bernhard, Johannes Gerschewski, [Anna Lührmann](https://sites.google.com/view/anna-luehrmann/) and Christian von Soest, University of Gothenburg, Varieties of Democracy Institute: Working Paper 2019:86. [PDF](https://www.v-dem.net/media/filer_public/6d/b2/6db2ed44-5d1e-4591-bff8-b3d101697656/v-dem_working_paper_2019_86.pdf)

**The Autocratic Trust Bias: Politically Sensitive Survey Items and Self-censorship** University of Gothenburg, Varieties of Democracy Institute: Working Paper 2017:49. [PDF](http://afrobarometer.org/sites/default/files/publications/Working%20papers/afropaperno176_autocratic_trust_bias.pdf)

**On the Road to Better Governance: The "Middle Class Particularism" and Quality of Government** The Quality of Government Institute Working Paper Series, 2014:09.

***

#### Policy Reports

**Making Development Work: The Quality of Government Approach*** w. Bo Rothstein, The Expert Group for Aid Studies (EBA) Report, 2015:07. [PDF](https://eba.se/wp-content/uploads/2015/12/Making_development_work_07.pdf)
